"""empty message

Revision ID: 24d3490f4c0a
Revises: ed55e1da3fbc
Create Date: 2022-11-07 23:33:06.377935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d3490f4c0a'
down_revision = 'ed55e1da3fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desparasitacion', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'desparasitacion', 'cliente', ['cliente_id'], ['id'])
    op.add_column('ficha__medica', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ficha__medica', 'cliente', ['cliente_id'], ['id'])
    op.add_column('vacuna', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacuna', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacuna', type_='foreignkey')
    op.drop_column('vacuna', 'cliente_id')
    op.drop_constraint(None, 'ficha__medica', type_='foreignkey')
    op.drop_column('ficha__medica', 'cliente_id')
    op.drop_constraint(None, 'desparasitacion', type_='foreignkey')
    op.drop_column('desparasitacion', 'cliente_id')
    # ### end Alembic commands ###
