"""empty message

Revision ID: a0da805e8561
Revises: 6121a346ec6e
Create Date: 2022-11-03 02:55:37.911435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0da805e8561'
down_revision = '6121a346ec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('agenda', sa.Column('medico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agenda', 'cliente', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'agenda', 'medico', ['medico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agenda', type_='foreignkey')
    op.drop_constraint(None, 'agenda', type_='foreignkey')
    op.drop_column('agenda', 'medico_id')
    op.drop_column('agenda', 'cliente_id')
    # ### end Alembic commands ###
