"""empty message

Revision ID: b57ef334b061
Revises: 2218ed157d83
Create Date: 2022-11-01 23:30:06.904561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57ef334b061'
down_revision = '2218ed157d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medico', 'telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medico', 'telefono',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
