"""empty message

Revision ID: e93d4e9b897e
Revises: 7b341695f43f
Create Date: 2022-11-01 03:18:39.694709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93d4e9b897e'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veterinaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_name', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('telefono')
    )
    op.add_column('user', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('vet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_type', ['user_type_id'], ['id'])
    op.create_foreign_key(None, 'user', 'veterinaria', ['vet_id'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'vet_id')
    op.drop_column('user', 'user_type_id')
    op.drop_table('veterinaria')
    op.drop_table('user_type')
    # ### end Alembic commands ###
