"""empty message

Revision ID: ea9067d31e7f
Revises: e2d254219f5b
Create Date: 2022-11-02 16:54:39.749383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9067d31e7f'
down_revision = 'e2d254219f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha__medica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=255), nullable=False),
    sa.Column('diagnostico', sa.String(length=255), nullable=False),
    sa.Column('estudios_medicos', sa.String(length=255), nullable=True),
    sa.Column('tratamiento', sa.String(length=255), nullable=False),
    sa.Column('recomendaciones', sa.String(length=255), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ficha__medica')
    # ### end Alembic commands ###
